mrjono1/joi-to-typescript

- src/__tests__/01.basic.ts
- src/__tests__/02.fromFile.ts
- src/__tests__/03.array.ts
- src/__tests__/04.multipleFiles.ts
- src/__tests__/05.enum.ts
- src/__tests__/06.alternatives.ts
- src/__tests__/07/AssertionCriteria.ts
- src/__tests__/08.allow.ts
- src/__tests__/09.unknown.ts
- src/index.ts
- src/parse.ts
- src/writeTypeFile.ts
- improve indentation
- do not generate documentation, that repeats the property name
- do not throw on joi.object() and joi.array()
- generates invalid code, when properties contain dot or other symbol, which results in invalid identifier without being put in quotes
- other fixes - see the example below
Consider this example
```js
const joi = require('joi');
const {convertSchema} = require('joi-to-typescript');
// console.log(convertSchema({}, joi.object().label('emptyObject')).content); // throws
console.log(convertSchema({}, joi.object({
// obj: joi.object(), // throws
nested: joi.object({a: joi.object({b: joi.string()})}),
date: joi.date().allow(null).description('This is date'),
'x.y': joi.string(),
// arr: joi.array(), // throws
bit: joi.boolean().allow(0, 1, '0', '1', null) …
```
> various fixes

- README.md
- src/__tests__/ignoreFiles/ignoreFiles.ts
- src/__tests__/ignoreFiles/schemas/OneSchema.ts
- src/__tests__/ignoreFiles/schemas/subDir/AddressSchema.ts
- src/__tests__/ignoreFiles/schemas/subDir/PersonSchema.ts
- src/__tests__/ignoreFiles/schemas/subDir2/EmployeeSchema.ts
- src/__tests__/subDirectories/subDirectories.ts
- src/convertFilesInDirectory.ts
- src/index.ts
- src/types.ts
- Add an option to ignore a list of files/folders
- Files are full filenames, directories are postfixed with a `/`
- Made sure tests for sub directories are cleaned up after each run properly
I decided to not use glob pattern matching as this package currently has no dependencies which I think is worthwhile keeping, and I didn't have the brain power tonight to figure out how [Glob](https://www.npmjs.com/package/glob) works or if it was even relevant to this problem
Addresses issue #18
> Ignore files option

- src/analyseSchemaFile.ts
- src/index.ts
When I linked `joi-to-typescript` as a dependency from the local folder, Node would try to load libraries "parse" and "analyseSchemaFile" instead of using the js file.
> Fix local source file imports to use relative paths

- src/__tests__/enum.ts
- src/parse.ts
- src/utils.ts
During generating types we encountered a string value that contained a single quote character. Since it was not escaped, the resulting TS file could not compile.
This PR adds `'` and `\` escaping, keeping string literals with single quotes as before.
> Escape ' and \ in generated string literals

- src/__tests__/joiExtensions/joiExtensions.ts
- src/__tests__/joiTypes.ts
- src/joiUtils.ts
- src/parse.ts
- currently unsupported Joi types are dropped from the interface
generation which also includes an Joi extensions added
- rather than doing that, attempt to workout a suitable TypeScript
type to use for them in the interface generation
- for Joi extensions, it is possible to add the base type in the
metadata in the same way that joi-to-swagger recommends:
const ExtendedJoi = Joi.extend(joi => {
const ext: Joi.Extension = {
type: 'objectId',
base: joi.string().meta({ baseType: 'string' })
};
return ext;
});
- use 'unknown' if no suitable type can be deduced
> Attempt to handle unsupported Joi types rather than omitting them

- README.md
- src/__tests__/unknown.ts
- src/parse.ts
- src/utils.ts
As a follow-up to https://github.com/mrjono1/joi-to-typescript/issues/168, I've extended the unknown type assertion to accept Joi schemas and updated and added a few fixes to the README.
So now, complex types will be properly reproduced when creating complex `Record`s and if `.pattern(Joi.string(), ...)` is used, the Joi validation will still be taken into account, but the generated type will be more accurate.
> Accept Joi schemas and strings in unknown type assertion

- src/__tests__/defaults/defaults.ts
- src/index.ts
- src/joiDescribeTypes.ts
- src/parse.ts
- src/types.ts
Thanks for this module, it has simplified my workflow considerably when defining APIs when combined with other modules.
As part of my project I have an API which defines a lot of default values on fields which are otherwise marked as optional (don't really want to force clients to fill in boilerplate cases). A middleware layer then fills in the defaults for anything not set by the client per the supplied schema.
As a result, it means a lot of the types generated include optional members which aren't really optional in the context the generated interfaces are referenced in.
In this PR I've added two new options to settings which, when enabled, do the following:
- Include the default value in the output type (mostly just a visibility thing, happy to drop this if unwanted)
- Mark fields …
> Extra options for working with fields containing defaults

- src/__tests__/override.ts
- src/parse.ts
no longer throws an error:
Joi.string().valid("val1", "val2").valid(Joi.override, "val3", "val4")
Joi.number().valid(12, 34).valid(Joi.override, 56, 78)
not implemented for: allow() invalid() or a mix
added (skipped) tests for existing bug/missing scenarios
> support for Joi.override in .valid()

- src/convertFilesInDirectory.ts
- src/index.ts
- src/parse.ts
Hi,
I have the following error when I use the newest version of the lib:
```
Error: Cannot find module 'write'
Require stack:
- XXXX\node_modules\joi-to-typescript\dist\main\parse.js
- XXXX\node_modules\joi-to-typescript\dist\main\analyseSchemaFile.js
- XXXX\node_modules\joi-to-typescript\dist\main\convertFilesInDirectory.js
- XXXX\node_modules\joi-to-typescript\dist\main\index.js
- XXXX\node_modules\@amd\generate-types\dist\index.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (XXXX\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require …
```
> Fix wrong import of write

- src/__tests__/noIndex/noIndex.ts
- src/__tests__/noIndex/schemas/FooBarSchema.ts
- src/__tests__/noIndex/schemas/InnerSchema.ts
- src/writeInterfaceFile.ts
The bug would cause imports of generated types to point to the root generation directory (still expecting an `index.ts` file as if `omitIndexFiles` was `false`) instead of pointing to each individually generated file.
Given the custom scheme (in `./Inner.ts`)
```
import Joi from 'joi';
export const InnerSchema = Joi.object({
hello: Joi.string()
}).meta({ className: 'InnerInterface' });
```
Imported with (in `./FooBar.ts`):
```
import Joi from 'joi';
import { InnerSchema } from './InnerSchema';
export const BarSchema = Joi.object({
id: Joi.number().required().description('Id').example(1),
inner: InnerSchema
}).meta({ className: 'Bar' });
```
Generates (in `interfaces/FooBar.ts`):
With bug (causing TS compilation issues):
```
import { InnerInterface } from '.'
```
After bug fix:
```
import …
```
> Fix an import-related bug introduced by the `omitIndexFiles` flag

- src/__tests__/alternatives/alternatives.ts
- src/parse.ts
This PR adds support for allowed values in handler of `Joi.alternatives()`
> Alternatives - add support for allowed values

- src/__tests__/array/array.ts
- src/__tests__/array/schemas/OneSparseSchema.ts
- src/joiDescribeTypes.ts
- src/parse.ts
Resolves https://github.com/mrjono1/joi-to-typescript/issues/324
> add handling for sparse arrays

- src/__tests__/defaults/defaults.ts
- src/parse.ts
As per title, if defaults are required and we manually pass the optional flag, at the moment the flag will be ignored.
> Fix the edge case where defaults are treated as required but we explicitely want to pass the `optional` flag.

- jest.config.cjs
- package.json
Move the `testEnvironment` config key to jest's own config file. 
Having multiple config sources is not allowed:
```
● Multiple configurations found:
* xxx/joi-to-typescript/jest.config.cjs
* `jest` key in xxx/joi-to-typescript/package.json
Implicit config resolution does not allow multiple configuration files.
Either remove unused config files or select one explicitly with `--config`.
Configuration Documentation:
https://jestjs.io/docs/configuration
```
> Move the `testEnvironment` config key to jest's own config file

- src/__tests__/defaults/defaults.ts
- src/parse.ts
The previous `wrapValue` function was incomplete, in the sense that strings with e.g. backslashes would be encoded in the wrong way. In the end, looking at the overall behavior of `wrapValue`, it seems to want to behave exactly in the same way as `JSON.stringify`, so it may be worth just replacing it once and for all.
> Use the plain JSON.stringify function to encode default values

- src/__tests__/alternatives/alternatives.ts
- src/__tests__/alternatives/schemas/OneSchema.ts
- src/__tests__/joiTypes.ts
- src/parse.ts
E.g. take this schema:
```
export const AlternativesWithFunctionSchema = Joi.alternatives([
Joi.function().minArity(2),
Joi.object({
json: Joi.any().required()
}),
Joi.object({
raw: Joi.string().required()
})
]).meta({ className: 'AlternativesWithFunctionInterface' });
```
Without brackets, a chain would have become
```
(...args: any[]) => any | {
json: any;
} | {
raw: string;
};
```
In this type, the whole `any | { json: any; } | { raw: string; }` is the return type of the function, which is wrong.
With brackets, it will be:
```
export type AlternativesWithFunctionInterface = ((...args: any[]) => any) | {
json: any;
} | {
raw: string;
};
```
There could be some more advanced logic to figure out if we want the brackets or not depending if we're using a union or not, but I feel it is even …
> Wraps function types in additional brackets to prevent broken union types

- src/__tests__/joiTypes.ts
- src/parse.ts
Previously, a definition like
```
export const TestSchema = Joi.function().meta({ className: 'Test' });
```
was exporting broken TS code:
```
(...args: any[]) => any;
```
It now exports:
```
export type Test = (...args: any[]) => any;
```
Note: this will conflict on merge with https://github.com/mrjono1/joi-to-typescript/pull/400. I'll take care of it if merged. Probably one test will fail.
> Add missing `export type` notation for unsupported types

- src/__tests__/allowValid/index.ts
- src/__tests__/description/index.ts
- src/__tests__/fromFile/fromFile.ts
- src/write.ts
I feel comments become more readable with spacing 🤔 
```
/**
* A simple description
* @example
* {
*   "hello": "world"
* }
* @example
* {
*   "hello": "world2"
* }
*/
export interface HelloTest {
hello?: string;
}
```
vs 
```
/**
* A simple description
* 
* @example
* {
*   "hello": "world"
* }
* @example
* {
*   "hello": "world2"
* }
*/
export interface HelloTest {
hello?: string;
}
```
> Add a spacing between JsDoc description and any additional examples

- src/__tests__/description/index.ts
- src/__tests__/description/schemas/OneSchema.ts
- src/write.ts
The use-case for this is plain readability when writing descriptions/examples, so they can be aligned with the various objects' keys in the code.
> Support description/example indentation

- src/__tests__/basic.ts
- src/parse.ts
- src/types.ts
There is a peculiar Joi detail where `Joi.object()` and `Joi.object({})` behave in different ways:
* `Joi.object()` allows by default any key/value pair.
* `Joi.object({})` DOES NOT allow by default any key/value pair.
When generating TS definitions, `Joi.object()` is perfectly represented by `object`, but `Joi.object({})` should be a forcefully empty object `{}`.
This PR addresses this last situation.
> Support raw empty objects

- src/__tests__/alternatives/alternatives.ts
- src/__tests__/alternatives/schemas/OneSchema.ts
- src/parse.ts
In the official docs: If no schemas are added, the type will not match any value except for undefined.
> Fix an edge case where the user does not pass ANY content to the `alternatives` function.

- src/__tests__/alternatives/alternatives.ts
- src/__tests__/alternatives/schemas/OneSchema.ts
- src/__tests__/defaults/defaults.ts
- src/__tests__/description/index.ts
- src/__tests__/description/schemas/OneSchema.ts
- src/__tests__/tuple/tuple.ts
- src/parse.ts
- src/write.ts
This is a bit of a massive PR but fixes a big issue which is that descriptions of `alternatives` schemas and tuples were not printed.
In the PR I also merged the `union` and `tuple` join operations because they behave precisely in the same way other than for separators order, which makes it simpler to handle the now more complex logic.
> Allow printing descriptions of objects contained in `alternatives` schemas and tuples' descriptions.

- README.md
- src/__tests__/alternatives/alternatives.ts
- src/__tests__/alternatives/schemas/OneSchema.ts
- src/__tests__/defaults/defaults.ts
- src/__tests__/description/index.ts
- src/__tests__/description/schemas/OneSchema.ts
- src/__tests__/tuple/tuple.ts
- src/parse.ts
- src/types.ts
- src/write.ts
Note: this is based/dependent on https://github.com/mrjono1/joi-to-typescript/pull/412
Add:
```
  /**
   * If defined, place every member of a union on a new line
   */
  unionNewLine?: boolean;
  /**
   * If defined, place every member of a tuple on a new line
   */
  tupleNewLine?: boolean;
```
When used, these settings can help formatting the generated code to improve its readability.
This PR was born because I was investigating a prettier bug that would cause JsDocs of union types to be "squashed", e.g. this code:
```
/**
* The items to iterate over.
*/
items:
/**
* An array to iterate over.
*/
| any[]
/**
* An object to iterate over.
*/
| object;
/**
* Another comment
*/
```
becomes:
```
/**
* The items to iterate over.
*/
items: /** <----------------- This is a bug
* An array to …
```
> Add `unionNewLine` and `tupleNewLine` settings to force newline styling for unions and tuples.

- src/analyseSchemaFile.ts
- src/types.ts
Also expose the original schema in the `ConvertedType` interface, which e.g. allows inspecting it in the `tsContentHeader` and `tsContentFooter` calls.
> Also expose the original schema in the `ConvertedType` interface

- src/__tests__/defaults/defaults.ts
- src/parse.ts
Ignore the `{"special": "deep"}` default value introduced by Joi when invoking the `default()` function without arguments.
Ref: https://github.com/hapijs/joi/blob/e7e9c5d18dafaa510a7ece02c225653db5fc998f/lib/manifest.js#L179
Without this fix, the generated TS code would look like:
```ts
export interface Test {"special":"deep"} | {
num: 1 | number;
str: "Test" | string;
strWithSpecialChars: "Test\\World$Hello🚀Hey\nYay" | string;
}
```
Note: there is an edge case here where if someone were to use the `{"special":"deep"}` values as default, this would not be printed in the generated type default. I think it's an acceptable "bug" because the Joi library dumps this value in the result of the describe function without providing additional information. 
---
Also, fix the generated types in case …
> Ignore the `{"special": "deep"}` default value introduced by Joi when invoking the `default()` function without arguments.

- README.md
- src/__tests__/defaults/defaults.ts
- src/parse.ts
- src/types.ts
- src/write.ts
- yarn.lock
Add the `supplyDefaultsInJsDoc` setting
If a field has a default value, add its stringified representation to the JsDoc using the `@default` annotation.
> Add the `supplyDefaultsInJsDoc` setting
